version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecs: circleci/aws-ecs@4.0.0

jobs:
  build-push-deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup
      - aws-ecs/initialize
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$CIRCLE_SHA1 -f nodeapp/Dockerfile .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$CIRCLE_SHA1
      - aws-ecs/update-service:
          family: ${ECS_TASK_DEFINITION_FAMILY}
          cluster: ${ECS_CLUSTER_NAME}
          container-image-name-updates: ${CONTAINER_NAME}=${ECR_REGISTRY}/${ECR_REPOSITORY}:${CIRCLE_SHA1}

workflows:
  build-and-deploy:
    jobs:
      - build-push-deploy:
          context: aws-context