version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  build-push-deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1 -f nodeapp/Dockerfile .
            docker push $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1

workflows:
  build-and-deploy:
    jobs:
      - build-push-deploy:
          context: aws-docker-context