version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecs: circleci/aws-ecs@4.0.0

jobs:
  build-push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          region: us-east-1
          role_arn: arn:aws:iam::058264355882:role/circle-ecs-role
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker build -t $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1 -f nodeapp/Dockerfile .
            docker push $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1
      # - run:
          # name: Update ECS Task Definition
          # command: |
            # Download the current task definition
            # aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FAMILY --query taskDefinition > task-definition.json
            # TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FAMILY)

            # Update the container image in the task definition
            # jq --arg CONTAINER_IMAGE "$DOCKER_HUB_USERNAME/$makinode-app-circle:$CIRCLE_SHA1" \
            #    '.containerDefinitions[0].image = $CONTAINER_IMAGE' task-definition.json > updated-task-definition.json
            # echo $TASK_DEFINITION | jq '.containerDefinitions[0].image = "'$DOCKER_HUB_USERNAME'/makinode-app-circle:'$CIRCLE_SHA1'"' > updated-task-definition.json

            # Register the updated task definition
            # aws ecs register-task-definition --family $ECS_TASK_DEFINITION_FAMILY --cli-input-json file://updated-task-definition.json

      # - run:
      #     name: Update ECS Task Definition
      #     command: |
      #       # Download the current task definition
      #       aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FAMILY --query 'taskDefinition' > task-definition.json

      #       # Update the container image in the task definition
      #       jq --arg CONTAINER_IMAGE "$DOCKER_HUB_USERNAME/$makinode-app-circle:$CIRCLE_SHA1" \
      #         '.containerDefinitions[0].image = $CONTAINER_IMAGE' task-definition.json > updated-task-definition.json

            # Register the updated task definition
            # aws ecs register-task-definition --cli-input-json file://updated-task-definition.json | jq -r '.taskDefinition.taskDefinitionArn' > task-definition-arn.txt
            # TASK_DEFINITION=$(aws ecs register-task-definition --cli-input-json file://updated-task-definition.json)
            # TASK_DEFINITION_ARN=$(echo $TASK_DEFINITION | jq -r '.taskDefinition.taskDefinitionArn')
            # echo $TASK_DEFINITION_ARN > task-definition-arn.txt

      - run:
          name: Update ECS Task Definition
          command: |
            # Download the current task definition
            aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_FAMILY --output-format json > task-definition.json

            # Extract the container name
            CONTAINER_NAME=$(jq -r '.containerDefinitions[0].name' task-definition.json)

            # Update the container image in the task definition
            jq --arg CONTAINER_IMAGE "$DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1" \
              '.containerDefinitions[0].image = $CONTAINER_IMAGE' task-definition.json > updated-task-definition.json

            # Register the updated task definition
            # aws ecs register-task-definition \
            #   --family $ECS_TASK_DEFINITION_FAMILY \
            #   --container-definitions file://updated-task-definition.json \
            #   --output text \
            #   --query 'taskDefinition.taskDefinitionArn' > task-definition-arn.txt

      - aws-ecs/update_task_definition_from_json:
          task_definition_json: updated-task-definition.json

      - aws-ecs/update_service:
          family: $ECS_TASK_DEFINITION_FAMILY
          cluster: $ECS_CLUSTER_NAME
          container_image_name_updates: container="$CONTAINER_NAME, tag=$CIRCLE_SHA1"
          # "container=$CONTAINER_NAME,tag=$CIRCLE_SHA1"

      # - run:
      #     name: Update ECS Service
      #     command: |
      #       # Update the ECS service with the new task definition
      #       aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $ECS_TASK_DEFINITION_FAMILY
      #       aws ecs wait services-stable --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME


workflows:
  build-and-push:
    jobs:
      - build-push:
          context: aws-docker-context