version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  build-push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          region: us-east-1
          role_arn: arn:aws:iam::058264355882:role/circle-ecs-role

      # Build and push Docker image
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker build -t $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1 -f nodeapp/Dockerfile .
            docker push $DOCKER_HUB_USERNAME/makinode-app-circle:$CIRCLE_SHA1

      # Download, Update, and Register ECS Task Definition
      - run:
          name: Update ECS Task Definition
          command: |
            # Get the latest revision of the task definition
            # LATEST_REVISION=$(aws ecs list-task-definitions --family-prefix makinode-app-task --sort DESC --max-items 1 --query 'taskDefinitionArns[0]' --output text)
            LATEST_REVISION=$(aws ecs list-task-definitions --family makinode-app-task --sort-order DESCENDING --max-items 1 | jq -r '.taskDefinitionArns[0]')

            # Download the current task definition
            TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $LATEST_REVISION)

            # Update the container image in the task definition
            echo $TASK_DEFINITION | jq '.containerDefinitions[0].image = "'$DOCKER_HUB_USERNAME'/makinode-app-circle:'$CIRCLE_SHA1'"' > updated-task-definition.json
            cat updated-task-definition.json

            # Register the updated task definition
            aws ecs register-task-definition --cli-input-json file://updated-task-definition.json

      # Update ECS Service
      - run:
          name: Update ECS Service
          command: |
            # Update the ECS service with the new task definition
            aws ecs update-service --cluster makinode-app-cluster --service makinode-app-service --task-definition $LATEST_REVISION
            aws ecs wait services-stable --cluster makinode-app-cluster --services makinode-app-service

workflows:
  build-and-push:
    jobs:
      - build-push:
          context: aws-docker-context